Fixed Unsale Bug
blank038/ServerMarket pull request #13
Opened 2024-06-08 13:26 UTC by MSCMDD

修复了商品在下架时不会转存到暂存库的bug（亦或是在背包满的时候下架，物品凭空会消失的bug）

2024-06-08 13:27 UTC, MSCMDD commented
#12

2024-06-09 08:13 UTC, blank038 commented on bukkit/src/main/java/com/blank038/servermarket/api/entity/MarketData.java
> +                                ServerMarket.getStorageHandler().addItemToStore(buyer.getUniqueId(), sale.getSaleItem(), "buy");
```suggestion
                                ServerMarket.getStorageHandler().addItemToStore(buyer.getUniqueId(), sale.getSaleItem(), "unsale");
```

2024-06-09 08:17 UTC, blank038 requested changes

2024-06-09 08:17 UTC, blank038 commented on bukkit/src/main/java/com/blank038/servermarket/api/entity/MarketData.java
> +                                ServerMarket.getStorageHandler().addItemToStore(buyer.getUniqueId(), sale.getSaleItem(), "buy");
明确来源是否会更好呢？

2024-06-09 09:47 UTC, blank038 approved these changes

2024-06-09 09:47 UTC, blank038 commented
感谢，此 PR 会推送至下个版本中。

2024-06-09 09:49 UTC, MSCMDD commented
CV编程忘改力QAQ

2024-06-09 09:52 UTC, merged